# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-unknown-linux-gnu.test-dependencies]
  devDep = { path = "./devDep" }

[target.x86_64-w64-mingw32.test-dependencies]
  devDep = { path = "./devDep" }

[target.x86_64-apple-darwin.test-dependencies]
  devDep = { path = "./devDep" }

[target.aarch64-apple-darwin.test-dependencies]
  devDep = { path = "./devDep" }
