# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  a0 = {path = "../a0", version = "1.0.0"}
  a1 = {path = "../a1", version = "1.0.0"}
  a2 = {path = "../a2", version = "1.0.0"}
  a4 = {path = "../a4", version = "1.0.0"}
  a5 = {path = "../a5", version = "1.0.0"}
  a6 = {path = "../a6", version = "1.0.0"}
  a7 = {path = "../a7", version = "1.0.0"}
  a8 = {path = "../a8", version = "1.0.0"}
  a9 = {path = "../a9", version = "1.0.0"}

[package]
  cjc-version = "0.25.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "a3"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target]
  aarch64-hm-gnu = {compile-option = "-B/opt/RTOS_V2X/301.1.0/arm64le_hm_pro/bin -B/opt/RTOS_V2X/301.1.0/arm64le_hm_pro/sdk/usr/lib -L/opt/RTOS_V2X/301.1.0/arm64le_hm_pro/gnu64/aarch64-hongmeng-musl/lib64"}
