# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

feature1 = "enable" # "disable"
# line comment 1
feature2 = "enable" # "disa
feature3 = "#"
feature4 = "\" # "
feature5 = "#" # d

# line comment 2
