# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  pro1 = {path = "./pro1"}
  pro2 = {path = "./pro2"}

[package]
  cjc-version = "0.35.2"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "cj004"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[profile]
  build = {incremental = false, lto = ""}
  customized-option = {cfg2 = "-g"}
  test = {}
