// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
package lib
public class C {
    public init() {}
    public exclave init(this @local!) { }

    public static func bar() { }
}
public type Al = C
public type F = Int64