# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.55.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "pro2"
  output-type = "static"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
[target.cjvm.debug]
  override-compile-option = "-O2"
[target.cjvm.release]
  override-compile-option = "-O2"
[target.x86_64-unknown-linux-gnu.debug]
  override-compile-option = "-O2"
[target.x86_64-unknown-linux-gnu.release]
  override-compile-option = "-O2"
[target.x86_64-w64-mingw32.debug]
  override-compile-option = "-O2"
[target.x86_64-w64-mingw32.release]
  override-compile-option = "-O2"
[target.x86_64-apple-darwin.debug]
  override-compile-option = "-O2"
[target.x86_64-apple-darwin.release]
  override-compile-option = "-O2"
[target.aarch64-apple-darwin.debug]
  override-compile-option = "-O2"
[target.aarch64-apple-darwin.release]
  override-compile-option = "-O2"
[target.aarch64-unknown-linux-gnu.debug]
  override-compile-option = "-O2"
[target.aarch64-unknown-linux-gnu.release]
  override-compile-option = "-O2"