# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "0.65.2"
  name = "primary"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  cmp = { path = "../cmp" }

[profile]
  experimental = true

[[source-set]]
  src-dir = "./common"
  features = [ ]

[[source-set]]
  src-dir = "./a"
  features = [ "user.primary.a" ]

[[source-set]]
  src-dir = "./b"
  features = [ "user.primary.b" ]

[[feature]]
name = "user.primary.a"
mapping = [ "user.cmp.a" ]

[[feature]]
name = "user.primary.b"
mapping = [ "user.cmp.b" ]