# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
members = ["boo"]

[target.x86_64-unknown-linux-gnu.dependencies]
aoo = { path = "aoo" }

[target.x86_64-w64-mingw32.dependencies]
aoo = { path = "aoo" }

[target.x86_64-apple-darwin.dependencies]
aoo = { path = "aoo" }

[target.aarch64-apple-darwin.dependencies]
aoo = { path = "aoo" }
