/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package upstream

public class SimpleStaticVarClass {
    public init() {
    }
    public static let appName: String = "MyApp"

    public static var counter: Int64 = 0i64
}

public class HelperClass {
    public init() {
    }
}

public struct HelperStruct {
    public var x: Int64 = 0i64

    public init() {
    }
}

public class MutableStaticVarClass {
    public init() {
    }
    public static var config: String = "default"
}

public class AnnotatedStaticVarClass {
    public init() {
    }

    @Deprecated
    public static let version: String = "1.0"
}
