# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
cj_res = { path = "./cj_res" }
sensor_mp = { path = "./sensor_mp" }

[package]
cjc-version = "1.0.0"
compile-option = ""
description = "nothing here"
link-option = ""
name = "simple_ui"
output-type = "dynamic"
target-dir = ""
version = "1.0.0"
package-configuration = {}


[[source-set]]
name = "common"
src-dir = "./src/common"
features = []

[[source-set]]
name = "android"
src-dir = "./src/android"
features = ["os.android"]

[[source-set]]
name = "ohos"
src-dir = "./src/ohos"
features = ["os.ohos"]


