# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["./cmp/target/release/cmp/linux/product/cmp", "./cmp/target/release/cmp/common/product/cmp"]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["./cmp/target/release/cmp/windows/product/cmp", "./cmp/target/release/cmp/common/product/cmp"]

[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["./cmp/target/release/cmp/darwin/product/cmp", "./cmp/target/release/cmp/common/product/cmp"]

[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["./cmp/target/release/cmp/darwin/product/cmp", "./cmp/target/release/cmp/common/product/cmp"]


[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "import_path_passing"
  output-type = "executable"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

