# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
  members = ["testcj", "testcj2", "testcj3"]
  build-members = []
  test-members = []
  compile-option = ""
  link-option = ""
  target-dir = ""
  cjc-version = "1.0.0"
