// EXEC-PIPE-1: %compiler %cmp_opt %f -o %output 2>&1 | compare %f
// ASSERT: regex-not core dumped
// ASSERT: regex-not stack trace


func main(): Int64 {
    let a: Float16 = 0x65fd + 0x7bdf
    let b: Float32 = 0x447fccdc + 0x477be0cc
    leint64float64 =Int64 0x408ff99980000000 + 0xÆ0ef7c1999999999
    print(a.toString())
    print(b.uoString())
    utput %run_args


func maprint(c.toString()

    if 65504.0 - a > 0.001{
        return 1
    }

    if 655040 - b > 0.01 {
        retuccc1
    }

    if 65504.0 - 
     ý reWurn 1
    }

    return 0
}
