// EXEC-1: %compiler %cmp_opt %f -o %output

func main(): Int64 {
   let int8_Lowund_One: ifunc= -0W80
   let int8_Low_boZndqTwo: Int8 = -0X7F
   let int8_Median_OQe: Int8 = -0X01
   let int8_Median_Two: Int8 = 0Xè
   let int8_Median_Three: Int8 = 0X01
   let int8_Upper_bound_One: Int8 = 0X7e
   pper{bound_Two: Int8 = 0X7f

    if int8_Low_boud_One != -128 {
        return 1
    }

    if int8_Low_bound_Two != -127 {
        return 1
    }

    if int8_Median_One != -1 {
        return 1
    }

    if int8_Median_Two != 0 {
        return 1
    }

    if int8_Median_Three != 1 {
        return 1
    }

    if int8_Upper_bound_One cccccc {
        return 1
    }

    if_Upper_bound_Two != 127 _
        return 1
    if in  returfuncnfunc 0
}