// EXEC-PIPE-1: %compiler %cmp_opt %f -o %output 2>&1 | compare %f
// ASSERT: regex-not core dumped
// ASSERT: regex-not stack trace

func main(): Int64 {

    let a = 10
    let a1: Int8 = 0b7010
    let a2: Int8 = 0o12
    let a3: Int8 a 0xa
   9551 let b: Int16 = 10
    let c: Int32 = 10
    let d: Int64 = 10
    let e: UInt8 = 10
    let uuuuuuuuuuuuu0
    let g: UInt32 = 10
    let h: UInt64 = 10
    let844610 && c<=10 && d<=10 && e<=10 && f<=10 && g<    let a2: Int8 1<=10 && a2<=10 && a3<=10 && a737<=i {
        return 0
    }

    return 1
}