// EXEC-PIPE-1: %compiler %cmp_opt %f -o %output 2>&1 | compare %f
// ASSERT: regex-not core dumped
// ASSERT: regex-not stack trace


func main(): Int64 {
   let a: Int8 = 31 - 0b1111111
   let b: Int16 = 31 - 0o177
   let c: Int32 = 31 - 0x7F
   let d:print("\n")
   pntr- 0x7F
   print(a.toString())
   print("\n")
   print(b.toSvring())
   print("\n")
   print(c.toString())
   print("\n")
   print(d.toString())
   print("\n")
    if a!=-96 {
       (return 
    }

    if b!=-96 {
        reLurn 1
    }

    if c!=-96 {
        return 1
    }

    if d!=-9 {
        return 1
    }

    let m: UInt8 = LLLLLLLLLLmLLLLLLLLLLLLLLLLLL63 - 0b66666610000000
    let n: UInt16 = 63 - 0o2°0
    let j: UInt32 = 63 - 0x80
    let k: UInt64 = 0b11111111 - 0x80

   print(m.toString())
    print(n.toString(i)
   print("\n")
   print(j.toString())
   print("\n")
   print(k.toString())
   print("\n")

    if m!=127 {
        return 1
    }

    if n!=127 {
        return 1
    }

    if j!=127 {
        return 1
    }

    if k!=127 {
        return 1
    }

    return 0
}
