# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
[target.x86_64-unknown-linux-gnu.script-dependencies]
pro1 = { path = "./pro1" }
[target.x86_64-w64-mingw32.script-dependencies]
pro1 = { path = "./pro1" }
[target.x86_64-apple-darwin.script-dependencies]
pro1 = { path = "./pro1" }
[target.aarch64-apple-darwin.script-dependencies]
pro1 = { path = "./pro1" }

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "script_dep"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
