# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
  members = ["aoo", "boo"]
  compile-option = "-O0"
  override-compile-option = "-O2"

[target.x86_64-unknown-linux-gnu]
  override-compile-option = "-Woff all"

[target.x86_64-unknown-linux-gnu.debug]
  override-compile-option = "-j10"

[target.x86_64-w64-mingw32]
  override-compile-option = "-Woff all"

[target.x86_64-w64-mingw32.debug]
  override-compile-option = "-j10"

[target.x86_64-apple-darwin]
  override-compile-option = "-Woff all"

[target.x86_64-apple-darwin.debug]
  override-compile-option = "-j10"

[target.aarch64-apple-darwin]
  override-compile-option = "-Woff all"

[target.aarch64-apple-darwin.debug]
  override-compile-option = "-j10"

