# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[ffi]
  [ffi.c]
    [ffi.c.test01]
      path = "./"
    [ffi.c.test02]
      path = "./"

[package]
  cjc-version = "0.43.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "demo"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[profile]
  build = {incremental = false, lto = "full"}
  customized-option = {}
  [profile.test]
    [profile.test.compilation-options]
      lto = "full"
