# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.54.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "a"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile.bench]
no-color = false
report-path = "bench_report" 
baseline-path = "./bench_report/benchmarks/bench-a.Bench_Param_02.csv"
show-all-output = true
verbose = false
build = { compile-option = "-O2", lto = "" }

[profile.test.env]
[profile.bench.env]
MY_ENV = { value = "abc" }
cjHeapSize = { value = "2GB", splice-type = "replace" }
PATH = { value = "./", splice-type = "prepend" }