# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  pro = {path = "pro", version = "2.0.1"}

[ffi]
  [ffi.c]
    [ffi.c.test01]
      path = "./"

[package]
  cjc-version = "0.27.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "demo"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}
