# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  compile-option = "--scan-dependency"
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[dependencies]

[target]
  [target.x86_64-w64-mingw32]
    [target.x86_64-w64-mingw32.bin-dependencies]
      package-option = {"pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"}

  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      package-option = {"pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"}

  [target.aarch64-unknown-linux-gnu]
    [target.aarch64-unknown-linux-gnu.bin-dependencies]
      package-option = {"pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"}

  [target.x86_64-apple-darwin]
    [target.x86_64-apple-darwin.bin-dependencies]
      package-option = {"pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"}

  [target.aarch64-apple-darwin]
    [target.aarch64-apple-darwin.bin-dependencies]
      package-option = {"pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"}

