# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "cal_demo"
  description = "nothing here"
  version = "1.0.0"
  output-type = "dynamic"

[dependencies]
  add_demo = "1.0.0"
  del_demo = "1.0.0"
