# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[dependencies]
  testing = { path = "./testing" }

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "mapping_to_dep_select"
  output-type = "executable"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  always-enabled-features = [ "user.mapping_to_dep_select._" ]

[[feature]]
name = "user.mapping_to_dep_select._"
mapping = [ "user.testing._0" ]

[[source-set]]
src-dir = "./src"
features = [ "user.mapping_to_dep_select._" ]