// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// EXEC: %compiler %f -o %output
// EXEC: %run %run_opt %output %run_args

class My<T> {
    func mymy(value: T @local!) {
    }
}

func foo() {
    var entries: My<Object> = My<Object>()
    let o = Object()@local!
    entries.mymy(o)
}
main() {}