# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "int64"
  version = "1.0.0"
  output-type = "dynamic"
  description = "nothing here"
  repository = "`"

[dependencies]
  aoo = { path = "aaa" }

[target.x86_64-unknown-linux-gnu.test-dependencies]
  boo = { git = "bbb" }

[target.x86_64-unknown-linux-gnu.debug.script-dependencies]
  coo = { path = "ccc" }