# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "dep"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


[target.x86_64-unknown-linux-gnu]
  link-option = "-L ./libtest -ltest"

[target.aarch64-unknown-linux-gnu]
  link-option = "-L ./libtest -ltest"

[target.x86_64-w64-mingw32]
  link-option = "-L ./libtest -ltest"
 
[target.x86_64-apple-darwin]
  link-option = "-L ./libtest -ltest"
 
[target.aarch64-apple-darwin]
  link-option = "-L ./libtest -ltest"
 