# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.


[target.x86_64-unknown-linux-gnu.ffi.c]
  test01 = {path = "./"}

[target.x86_64-unknown-linux-gnu.debug.ffi.c]
  test01 = {path = "./debug"}

[target.x86_64-unknown-linux-gnu.release.ffi.c]
  test01 = {path = "./release"}

[target.x86_64-w64-mingw32.ffi.c]
  test01 = {path = "./"}

[target.x86_64-w64-mingw32.debug.ffi.c]
  test01 = {path = "./debug"}

[target.x86_64-w64-mingw32.release.ffi.c]
  test01 = {path = "./release"}

[target.x86_64-apple-darwin.ffi.c]
  test01 = {path = "./"}

[target.x86_64-apple-darwin.debug.ffi.c]
  test01 = {path = "./debug"}

[target.x86_64-apple-darwin.release.ffi.c]
  test01 = {path = "./release"}

[target.aarch64-apple-darwin.ffi.c]
  test01 = {path = "./"}

[target.aarch64-apple-darwin.debug.ffi.c]
  test01 = {path = "./debug"}

[target.aarch64-apple-darwin.release.ffi.c]
  test01 = {path = "./release"}

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "demo"
  output-type = "executable"
  override-compile-option = ""
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
