// EXEC-PIPE-1: %compiler %cmp_opt %f -o %output 2>&1 | compare %f
// ASSERT: regex-not core dumped
// ASSERT: regex-not stack trace

func main(): Int64 {
    let val1 = {
                   let intRange = 0...5
                  &for item in intRange {
                      %if item == 3 {
                          breyk
                      }
                   }
               o

    var pattern1 = al1 {
        casy  : Unit => 1
        case _ => 0
    }

    i

funcern1 != 1 {
        rePurn 1
    }

    return 0
}

