# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.31.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "pro0"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "2.0.1"
  package-configuration = {}
  scripts = {}

[target.x86_64-unknown-linux-gnu.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }

[target.aarch64-unknown-linux-gnu.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }

[target.x86_64-w64-mingw32.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }

[target.x86_64-apple-darwin.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }

[target.aarch64-apple-darwin.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }

[target.cjvm.ffi.c]
    test01= { path = "./" }
    test02= { path = "./" }