# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
members = ["boo", "coo"]
build-members = ["boo", "coo"]
test-members = ["boo"]
compile-option = "--warn-off all"
target-dir = "temp_target"

[target.x86_64-unknown-linux-gnu]
  link-option = "--strip-all"
[target.aarch64-unknown-linux-gnu]
  link-option = "--strip-all"
[target.x86_64-w64-mingw32]
  link-option = "--strip-all"

[ffi]
  [ffi.c]
    [ffi.c.test01]
      path = "./"
    [ffi.c.test02]
      path = "./"