# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.35.2"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "pro1"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
    [package.package-configuration."pro1.pa"]
      compile-option = ""
      output-type = ""
  scripts = {}

[profile]
  build = {incremental = false, lto = ""}
  customized-option = {cfg1 = "--cfg=\"feature1=lion\"", cfg2 = "-g"}
  test = {}
