// EXEC: %compiler %cmp_opt %f -o %output
// EXEC: %run %run_opt %output %run_args
// random seed:1631160220125

func main(): Int64 {
    return 0;
}

external open class Class94 {
    static func func587() : Unit { // block id: 588
        Class632<Bool, Float64>.var638
    }
}
external open class Class632<T0, T1> {
    static prop let var638 : Unit { // block id: 639
        get() { // block id: 641
            ()
        }
    }
}
