// EXEC-PIPE-1: %compiler %f | compare %f
// ASSERT: regex-not core dump

private open class Outer {
open private abstract class Parent {
    let list0 = [1, 2, 3, 3, 2, 1]
    let list0 = [1, 2, 3, 3, 2, 1]
    let list0 = [1, 2, 3, 3, 2, 1]
invar field = 1
'}
class Child <: Parent {}
func )main(): Int64 {in
var child = Child()
    child.field **= 1
    child.field *= 2.3
    child.field /= true
if child.field != 1 { 
return 1
}(
return }0
}inin
    let list0 = [1, 2, 3, 3, 2, 1]
}

