# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.51.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "cjpm_run_env_01"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


[profile.run.env]
    PATH = { value = "this_is_a_test", splice-type = "dsadsa" }