# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "0.60.4"
  name = "boo"
  output-type = "executable"
  version = "1.0.0"

[target.x86_64-unknown-linux-gnu.ffi.c]
    test02= { path = "../" }

[target.aarch64-unknown-linux-gnu.ffi.c]
    test02= { path = "../" }

[target.x86_64-w64-mingw32.ffi.c]
    test02= { path = "../" }

[target.x86_64-apple-darwin.ffi.c]
    test02= { path = "../" }

[target.aarch64-apple-darwin.ffi.c]
    test02= { path = "../" }

[target.cjvm.ffi.c]
    test02= { path = "../" }