# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
members = ["../workspace_test_4/aoo"]
compile-option = "--warn-off all" 
target-dir = "temp_target" 

[profile.build]
lto = "full"
incremental = true 